"""1

Revision ID: fbd63b815db7
Revises: b5ecdb20df34
Create Date: 2023-01-22 09:32:08.680940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd63b815db7'
down_revision = 'b5ecdb20df34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
